USE [master]
GO
/****** Object:  Database [FastBook]    Script Date: 22/05/1395 11:34:49 ب.ظ ******/
CREATE DATABASE [FastBook]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FastBook', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\FastBook.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FastBook_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\FastBook_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [FastBook] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FastBook].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FastBook] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FastBook] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FastBook] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FastBook] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FastBook] SET ARITHABORT OFF 
GO
ALTER DATABASE [FastBook] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FastBook] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FastBook] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FastBook] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FastBook] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FastBook] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FastBook] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FastBook] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FastBook] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FastBook] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FastBook] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FastBook] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FastBook] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FastBook] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FastBook] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FastBook] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FastBook] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FastBook] SET RECOVERY FULL 
GO
ALTER DATABASE [FastBook] SET  MULTI_USER 
GO
ALTER DATABASE [FastBook] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FastBook] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FastBook] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FastBook] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [FastBook] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'FastBook', N'ON'
GO
USE [FastBook]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [FastBook]
GO
/****** Object:  User [admin]    Script Date: 22/05/1395 11:34:49 ب.ظ ******/
CREATE USER [admin] FOR LOGIN [admin] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[ITEM]    Script Date: 22/05/1395 11:34:49 ب.ظ ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITEM](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[ItemTypeId] [nvarchar](50) NULL,
	[PageId] [nvarchar](50) NULL,
	[LessonId] [nvarchar](50) NULL,
	[Title] [nvarchar](max) NULL,
	[Content] [nvarchar](max) NULL,
 CONSTRAINT [PK_ITEM] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ITEM_TYPE]    Script Date: 22/05/1395 11:34:49 ب.ظ ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITEM_TYPE](
	[_id] [int] NULL,
	[ITEM_TYPE_NAME] [nvarchar](max) NULL,
	[LANGUAGE] [nvarchar](max) NULL,
	[PAGE_TYPE_ID] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[LESSON]    Script Date: 22/05/1395 11:34:49 ب.ظ ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LESSON](
	[_id] [int] NULL,
	[LESSON_TITLE] [nvarchar](max) NULL,
	[LOGO] [varbinary](max) NULL,
	[COLOR] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PACK]    Script Date: 22/05/1395 11:34:49 ب.ظ ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PACK](
	[_id] [int] NULL,
	[METHOD_ID] [int] NULL,
	[PACK_NAME] [nvarchar](max) NULL,
	[SUBJECT_ID] [int] NULL,
	[LOGO] [varbinary](max) NULL,
	[COLOR] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PAGE]    Script Date: 22/05/1395 11:34:49 ب.ظ ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAGE](
	[_id] [int] NULL,
	[LESSON_ID] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PAGE_TYPE]    Script Date: 22/05/1395 11:34:49 ب.ظ ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAGE_TYPE](
	[_id] [int] NULL,
	[PAGE_TYPE_NAME] [nvarchar](max) NULL,
	[LANGUAGE] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[QUESTION]    Script Date: 22/05/1395 11:34:49 ب.ظ ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[QUESTION](
	[_id] [int] NULL,
	[ITEM_TYPE_ID] [int] NULL,
	[PAGE_ID] [int] NULL,
	[LESSON_ID] [int] NULL,
	[QUESTION_TITLE] [nvarchar](max) NULL,
	[COUNT_TRUE] [int] NULL,
	[COUNT_FALSE] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[QUESTION_DETAIL]    Script Date: 22/05/1395 11:34:49 ب.ظ ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[QUESTION_DETAIL](
	[_id] [int] NULL,
	[QUESTION_ID] [int] NULL,
	[ANSWER] [int] NULL,
	[IS_ANSWER] [int] NULL
) ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [FastBook] SET  READ_WRITE 
GO
